variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - prepare

# Stage: prepare
##############################################################################

docker:
  stage: prepare
  script:
    - export RUST_CHANNEL="nightly"
    - export RUSTY_LATEST=$(curl -s https://api.github.com/repos/hermitcore/libhermit-rs/releases/latest | grep tag_name | sed -E 's/.*"([^"]+)".*/\1/')"
    - echo ${RUSTY_LATEST}
    - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
    - docker build --build-arg LATEST=${RUSTY_LATEST} -t hermitcore/rustyhermit .
    - export RUST_DATE=$(docker run hermitcore/rustyhermit rustc --version | grep -oE "[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}")
    - export RUST_VER=$(docker run hermitcore/rustyhermit rustc --version | grep -oE "[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]")
    - export TAG1="${RUST_VER}-${RUST_CHANNEL}"
    - export TAG2="${RUST_CHANNEL}-${RUST_DATE}"
    - export TAG3="${RUST_CHANNEL}"
    - docker push hermitcore/rustyhermit
    - docker tag hermitcore/rustyhermit hermitcore/rustyhermit:$TAG1
    - docker push hermitcore/rustyhermit:$TAG1
    - docker tag hermitcore/rustyhermit hermitcore/rustyhermit:$TAG2
    - docker push hermitcore/rustyhermit:$TAG2
    - docker tag hermitcore/rustyhermit hermitcore/rustyhermit:$TAG3
    - docker push hermitcore/rustyhermit:$TAG3
  tags:
    - shell
    - linux
