variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - prepare

# Stage: prepare
##############################################################################

docker:
  stage: prepare
  script:
    - export RUST_CHANNEL="nightly"
    - export RUSTY_LATEST="$(curl -s https://api.github.com/repos/hermitcore/libhermit-rs/releases/latest | grep tag_name | sed -E 's/.*"([^"]+)".*/\1/')"
    - echo ${RUSTY_LATEST}
    - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" registry.git.rwth-aachen.de
    - docker build --no-cache --build-arg LATEST=${RUSTY_LATEST} -t registry.git.rwth-aachen.de/acs/public/hermitcore/hermitrust .
    - export RUST_DATE=$(date +"%Y-%m-%d")
    - export RUST_VER=$(docker run hermitcore/rustyhermit rustc --version | grep -oE "[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]")
    - export TAG1="${RUST_VER}-${RUST_CHANNEL}"
    - export TAG2="${RUST_CHANNEL}-${RUST_DATE}"
    - export TAG3="${RUST_CHANNEL}"
    - docker push registry.git.rwth-aachen.de/acs/public/hermitcore/hermitrust
    - docker tag registry.git.rwth-aachen.de/acs/public/hermitcore/hermitrust registry.git.rwth-aachen.de/acs/public/hermitcore/hermitrust:$TAG1
    - docker push registry.git.rwth-aachen.de/acs/public/hermitcore/hermitrust:$TAG1
    - docker tag registry.git.rwth-aachen.de/acs/public/hermitcore/hermitrust registry.git.rwth-aachen.de/acs/public/hermitcore/hermitrust:$TAG2
    - docker push registry.git.rwth-aachen.de/acs/public/hermitcore/hermitrust:$TAG2
    - docker tag registry.git.rwth-aachen.de/acs/public/hermitcore/hermitrust registry.git.rwth-aachen.de/acs/public/hermitcore/hermitrust:$TAG3
    - docker push registry.git.rwth-aachen.de/acs/public/hermitcore/hermitrust:$TAG3
  tags:
    - shell
    - linux
