language: generic
services:
- docker
script:
- export RUST_CHANNEL="nightly"
- if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  fi
- docker build --build-arg CHANNEL=${RUST_CHANNEL} -t hermitcore/rustyhermit .
- export RUST_DATE=$(docker run -it hermitcore/rustyhermit rustc --version | grep -oE "[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}")
- export RUST_VER=$(docker run -it hermitcore/rustyhermit --version | grep -oE "[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]")
- export TAG1="${RUST_VER}-${RUST_CHANNEL}"
- export TAG2="${RUST_CHANNEL}-${RUST_DATE}"
- export TAG3="${RUST_CHANNEL}"
after_success: |
  if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
    docker push hermitcore/rustyhermit
    docker tag hermitcore/rustyhermit hermitcore/rustyhermit:$TAG1
    docker push hermitcore/rustyhermit:$TAG1
    docker tag hermitcore/rustyhermit hermitcore/rustyhermit:$TAG2
    docker push hermitcore/rustyhermit:$TAG2
    docker tag hermitcore/rustyhermit hermitcore/rustyhermit:$TAG3
    docker push hermitcore/rustyhermit:$TAG3
  fi
notifications:
  email:
    on_success: change
    on_failure: always
